GENRES = [
    "Action",
    "Adventure",
    "Animation",
    "Anime",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "Horror",
    "Mystery",
    "Romance",
    "Seasonal",
]
LANGUAGES = {
    "English": "en",
    "Foreign": "foreign",
    "All": "all",
    "French": "fr",
    "Japanese": "ja",
    "Spanish": "es",
    "Italian": "it",
    "German": "de",
    "Chinese": "zh",
    "Korean": "ko",
    "Cantonese": "cn",
    "Hindi": "hi",
    "Swedish": "sv",
    "Portuguese": "pt",
    "Russian": "ru",
    "Romanian": "ro",
    "Polish": "pl",
    "Turkish": "tr",
    "Dutch": "nl",
    "Thai": "th",
    "Danish": "da",
    "Indonesian": "id",
    "Tamil": "ta",
    "Norwegian": "no",
    "Arabic": "ar",
    "Telugu": "te",
    "Finnish": "fi",
    "Czech": "cs",
    "Hungarian": "hu",
    "Vietnamese": "vi",
    "Tagalog": "tl",
    "Persian": "fa",
    "Hebrew": "he",
    "Punjabi": "pa",
    "Ukrainian": "uk",
    "Malayalam": "ml",
    "Estonian": "et",
    "Greek": "el",
    "Bangla": "bn",
    "Malay": "ms",
    "Kannada": "kn",
    "Catalan": "ca",
    "Icelandic": "is",
    "Slovak": "sk",
    "Serbian": "sr",
    "Urdu": "ur",
    "Marathi": "mr",
    "Lithuanian": "lt",
    "Latvian": "lv",
    "Georgian": "ka",
    "Croatian": "hr",
    "Bulgarian": "bg",
    "Afrikaans": "af",
    "Bosnian": "bs",
    "Macedonian": "mk",
    "Galician": "gl",
    "Wolof": "wo",
    "Zulu": "zu",
    "Kurdish": "ku",
    "Basque": "eu",
    "Serbo-Croatian": "sh",
    "Irish": "ga",
    "Kazakh": "kk",
    "Albanian": "sq",
    "Tibetan": "bo",
    "Yoruba": "yo",
    "Gujarati": "gu",
    "Swahili": "sw",
    "Slovenian": "sl",
    "Amharic": "am",
    "Armenian": "hy",
    "Khmer": "km",
    "Mongolian": "mn",
    "Yiddish": "yi",
    "Pashto": "ps",
    "Southern Sotho": "st",
    "Cantonese (Yue)": "yue",
    "Xhosa": "xh",
    "Nepali": "ne",
    "Javanese": "jv",
    "Abkhazian": "ab",
    "Latin": "la",
    "Ossetic": "os",
    "Maori": "mi",
    "Akan": "ak",
    "Haitian Creole": "ht",
    "Welsh": "cy",
    "Maltese": "mt",
    "cmn": "cmn",
    "Burmese": "my",
    "Lao": "lo",
    "Bambara": "bm",
    "Dzongkha": "dz",
    "Northern Sami": "se",
    "Norwegian Bokmål": "nb",
    "Afar": "aa",
    "Luxembourgish": "lb",
    "Kyrgyz": "ky",
    "Azerbaijani": "az",
    "Somali": "so",
    "Inuktitut": "iu",
    "Ganda": "lg",
    "Belarusian": "be",
    "Igbo": "ig",
    "No linguistic content": "zxx",
    "Filipino": "fil",
    "Twi": "tw",
    "Kinyarwanda": "rw",
    "Odia": "or",
    "American Sign Language": "ase",
    "Min Nan Chinese": "nan",
    "ber": "ber",
    "qag": "qag",
    "Swiss German": "gsw",
    "Lingala": "ln",
    "Iban": "iba",
    "Cree": "cr",
    "Tswana": "tn",
    "qab": "qab",
    "Romany": "rom",
    "Sanskrit": "sa",
    "ukl": "ukl",
    "Uyghur": "ug",
    "kvk": "kvk",
    "Oromo": "om",
    "myn": "myn",
    "Uzbek": "uz",
    "Fulah": "ff",
}
DOWNLOAD_PATH = "/Users/gijomathew/Downloads/"
